name: Update README

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Use the REPO_ACCESS_TOKEN here

      - name: Update README
        run: |
          sudo apt-get install -y tzdata
          d=$(TZ='Asia/Kathmandu' date +'%Y-%m-%d %I:%M %p')
          sed -i "s/^.*Last updated: .*$/<p align=\"center\">Last updated: $d<\/p>/g" README.md

      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git commit -am "Update README" && git push origin || echo "No changes to commit"
